# Site settings
#header: Jatomis Stevenson
title: Editorial
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Los Angeles
state: California
zip_code: 
country: United States of America
phone: 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

# Excerpt separator definition
excerpt_separator: "<!--excerpt-->"


# Collections settings (Allows the menus to work properly)
collections:
  anchors:
    submenu:
    another_submenu:
    output: true
    permalink: /:name
  mini_articles:
    output: true
    permalink: /:name

  

# port
#port: 3000